admin:
  path:     /admin
  defaults: { _controller: AppBundle:Admin:Admin }
  requirements:
    _method: GET

admin_test:
  path:     /admin/testlogin
  defaults: { _controller: AppBundle:Admin:AdminTestlogin }
  requirements:
    _method: GET

admin_create:
  path:     /admin/create
  defaults: { _controller: AppBundle:Brand:CreateBrandAbdModels }
  requirements:
    _method: GET

admin_list:
  path:     /admin/list
  defaults: { _controller: AppBundle:Admin:AdminList }
  requirements:
    _method: GET